### ISSUE TITLE
Request from a Chinese student

### ISSUE THREAD

**Issue by gsk21dx** [CodingWithTashi/LundupAdventure#1]
Dear ཁུན་ཁྲུན་ཁི་ཐ་ཧྲི། ,

I really appreciate that you are free to see this message. I am going to develop a Tibetan game, a digital virtual gamification display of traditional games in Tibet. I am currently a rookie and would like to get some advice and help from you. I was very surprised to see your project because there are very few resources for Tibetan games. So I must seize the opportunity to make a request to you, and please forgive me if I disturb you.

May you be well.

Your follower;

gsk

**Comment by CodingWithTashi** [comment]
Hi @gsk21dx,
I am glad that you came across my project. I built this game using the unity game engine last year.
Currently, I am not active in this project. Feel free to fork and take a look at the source code.

You can also reach out to me directly by pinging me by email at developer.kharag@gmail.com.

Regards
Tashi
